name: CI/CD Pipeline for Node.js Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List files in the directory
        run: |
          echo "Listing contents of the repository root:"
          ls -alh

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Build and Push Docker Image to ECR
        run: |
          COMMIT_ID=$(git rev-parse --short=7 ${{ github.sha }})
          echo "Building Docker image with tag: $COMMIT_ID"
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/pocrepo:$COMMIT_ID --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -f Application/Dockerfile Application/
          echo "Logging into Amazon ECR..."
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com
          echo "Pushing Docker image to ECR..."
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/pocrepo:$COMMIT_ID
          echo "Docker push completed."

      - name: Update Helm values.yaml
        run: |
          echo "Updating Helm values.yaml with new image..."
          echo "image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/pocrepo:${{ steps.build-and-deploy.outputs.COMMIT_ID }}" > ./helm/chart/values.yaml
          cat ./helm/chart/values.yaml

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region us-west-2 --name EKSWorkshop-cluster
        shell: /usr/bin/bash -e {0}
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_REGION: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Helm Chart to EKS
        run: |
          echo "Deploying application using Helm..."
          helm upgrade --install my-website1 ./helm/chart -f ./helm/chart/values.yaml
          echo "Helm deployment completed."
        shell: /usr/bin/bash -e {0}
        env:
          AWS_DEFAULT_REGION: us-west-2
          AWS_REGION: us-west-2
